# Generated by Django 3.2.7 on 2021-09-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_rename_complete_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='decription',
            new_name='description',
        ),
    ]
